// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBReJ91cdKkQesszLBFRgJnljRlvZCQjB4',
    appId: '1:827324211638:web:9b240f0dec5656fd692117',
    messagingSenderId: '827324211638',
    projectId: 'blogapp3-ac954',
    authDomain: 'blogapp3-ac954.firebaseapp.com',
    storageBucket: 'blogapp3-ac954.appspot.com',
    measurementId: 'G-L63JNVLKBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMzqP95RvNvgyuZRtLR6KF8s0KW5HoVM',
    appId: '1:827324211638:android:5505dc4bbd26f545692117',
    messagingSenderId: '827324211638',
    projectId: 'blogapp3-ac954',
    storageBucket: 'blogapp3-ac954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcSJorSchGR1XJPD7fQvfJXnAx3F_VMfg',
    appId: '1:827324211638:ios:3b96b5af9a2d571e692117',
    messagingSenderId: '827324211638',
    projectId: 'blogapp3-ac954',
    storageBucket: 'blogapp3-ac954.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );
}
